name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ubuntu
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws/v8a6y7y7

      - name: Build & Push Backend Docker Image
        run: |
          docker build -t backend ./spreadb_project-main
          docker tag backend:latest public.ecr.aws/v8a6y7y7/spreadb-public:latest
          docker push public.ecr.aws/v8a6y7y7/spreadb-public:latest

      - name: Build Frontend
        run: |
          cd spreadb_frontend-main
          npm install
          CI=false npm run build

      - name: Upload frontend files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "spreadb_frontend-main/build/*"
          target: "/home/ubuntu/frontend-temp/"
          rm: true   # Remove existing files before copying

      - name: Connect & Deploy on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Backend Deploy ==="
            docker pull public.ecr.aws/v8a6y7y7/spreadb-public:latest

            docker stop backend || true
            docker rm backend || true

            docker run -d --name backend -p 3001:3001 \
              -e NODE_ENV=production \
              public.ecr.aws/v8a6y7y7/spreadb-public:latest

            echo "=== Frontend Deploy ==="
            sudo rsync -av --delete /home/ubuntu/frontend-temp/ /usr/share/nginx/html/
            sudo systemctl restart nginx